//CODE-GEN FILE
//This file is generated from subfolder "meta".
//Changes to this file must be made in the meta project.

#include <QString>
#include <QHash>

enum NodeType {
	ABS,
	ADDITION,
	ARGS,
	BACKSLASH,
	BOOLEANS,
	BRACKET_GROUPING,
	CALL,
	COMPLEX_NUMS,
	CONTINUOUS,
	CROSS,
	DAGGER,
	DECREMENT,
	DEFINE_EQUALS,
	DIVIDE,
	DOT,
	EMPTY_SET,
	EQUAL,
	EXPR_STMT,
	FACTORIAL,
	FORWARDSLASH,
	GREATER,
	GREATER_EQUAL,
	IDENTIFIER,
	IMPLICIT_MULTIPLY,
	IN,
	INCREMENT,
	INFTY,
	INTEGERS,
	INTEGRAL,
	INTERSECTION,
	LESS,
	LESS_EQUAL,
	LOGICAL_AND,
	LOGICAL_NOT,
	LOGICAL_OR,
	MODULUS,
	MULTIFACTORIAL,
	MULTIPLICATION,
	NATURAL_NUMS,
	NEGATIVE_REALS,
	NORM,
	NOT_EQUAL,
	NOT_IN,
	NUMBER,
	PAREN_GROUPING,
	POSITIVE_REALS,
	POWER,
	QUATERNIONS,
	RANGE_CLOSE_CLOSE,
	RANGE_CLOSE_OPEN,
	RANGE_OPEN_CLOSE,
	RANGE_OPEN_OPEN,
	RATIONAL_NUMS,
	REALS,
	SET_LITERAL,
	SUBSCRIPT_ACCESS,
	SUBSCRIPT_PARTIAL,
	SUBTRACTION,
	SUMMATION,
	TICK_DERIVATIVE,
	TRANSPOSE,
	TYPED_BINOMIAL,
	TYPED_CASES,
	TYPED_FRACTION,
	TYPED_MATRIX,
	TYPED_POWER,
	TYPED_ROOT,
	TYPED_SQRT,
	UNARY_MINUS,
	UNION,
	VEE,
	WEDGE,
};

static constexpr int NodeType_Size = 72;

static const QHash<NodeType, QString> labels {
	{ABS, "|⋅|"},
	{ADDITION, "+"},
	{ARGS, "args"},
	{BACKSLASH, "\\\\"},
	{BOOLEANS, "𝔹"},
	{BRACKET_GROUPING, "group[]"},
	{CALL, "f()"},
	{COMPLEX_NUMS, "ℂ "},
	{CONTINUOUS, "ℂⁿ"},
	{CROSS, "×"},
	{DAGGER, "†"},
	{DECREMENT, "x⁻"},
	{DEFINE_EQUALS, "≔"},
	{DIVIDE, "÷"},
	{DOT, "⋅"},
	{EMPTY_SET, "∅"},
	{EQUAL, "="},
	{EXPR_STMT, "expr\\nstmt"},
	{FACTORIAL, "!"},
	{FORWARDSLASH, "/"},
	{GREATER, ">"},
	{GREATER_EQUAL, "≥"},
	{IDENTIFIER, "id: "},
	{IMPLICIT_MULTIPLY, "*imp"},
	{IN, "∈"},
	{INCREMENT, "x⁺"},
	{INFTY, "∞"},
	{INTEGERS, "ℤ"},
	{INTEGRAL, "∫"},
	{INTERSECTION, "∩"},
	{LESS, "<"},
	{LESS_EQUAL, "≤"},
	{LOGICAL_AND, "∧"},
	{LOGICAL_NOT, "¬"},
	{LOGICAL_OR, "∨"},
	{MODULUS, "%"},
	{MULTIFACTORIAL, "!"},
	{MULTIPLICATION, "*"},
	{NATURAL_NUMS, "ℕ"},
	{NEGATIVE_REALS, "ℝ⁻"},
	{NORM, "‖⋅‖"},
	{NOT_EQUAL, "≠"},
	{NOT_IN, "∉"},
	{NUMBER, ""},
	{PAREN_GROUPING, "group()"},
	{POSITIVE_REALS, "ℝ⁺"},
	{POWER, "^"},
	{QUATERNIONS, "ℍ"},
	{RANGE_CLOSE_CLOSE, "range[]"},
	{RANGE_CLOSE_OPEN, "range[)"},
	{RANGE_OPEN_CLOSE, "range(]"},
	{RANGE_OPEN_OPEN, "range()"},
	{RATIONAL_NUMS, "ℚ"},
	{REALS, "ℝ"},
	{SET_LITERAL, "{}"},
	{SUBSCRIPT_ACCESS, "xᵢ"},
	{SUBSCRIPT_PARTIAL, "∂"},
	{SUBTRACTION, "-"},
	{SUMMATION, "Σ"},
	{TICK_DERIVATIVE, "'"},
	{TRANSPOSE, "⊤"},
	{TYPED_BINOMIAL, "⁜b"},
	{TYPED_CASES, "⁜c"},
	{TYPED_FRACTION, "⁜f"},
	{TYPED_MATRIX, "⁜⊞"},
	{TYPED_POWER, "⁜^"},
	{TYPED_ROOT, "⁜√"},
	{TYPED_SQRT, "⁜√"},
	{UNARY_MINUS, "-"},
	{UNION, "∪"},
	{VEE, "∨"},
	{WEDGE, "∧"},
};

static const QHash<NodeType, QString> node_color {
	{BOOLEANS, "orange"},
	{COMPLEX_NUMS, "orange"},
	{EMPTY_SET, "orange"},
	{IDENTIFIER, "lightblue"},
	{INFTY, "orange"},
	{INTEGERS, "orange"},
	{NATURAL_NUMS, "orange"},
	{NEGATIVE_REALS, "orange"},
	{NUMBER, "orange"},
	{POSITIVE_REALS, "orange"},
	{QUATERNIONS, "orange"},
	{RATIONAL_NUMS, "orange"},
	{REALS, "orange"},
};

