#include <string>
#include <QString>
#include <QHash>

enum NodeType {
	REALS,
	POSITIVE_REALS,
	NEGATIVE_REALS,
	INTEGERS,
	NATURAL_NUMS,
	IDENTIFIER,
	NUMBER,
	ADDITION,
	SUBTRACTION,
	UNARY_MINUS,
	MULTIPLICATION,
	CROSS,
	DOT,
	IN,
	NOT_IN,
	EQUAL,
	NOT_EQUAL,
	SUMMATION,
	LOGICAL_NOT,
	LOGICAL_AND,
	LOGICAL_OR,
	INTEGRAL,
	FACTORIAL,
	MULTIFACTORIAL,
	GREATER,
	LESS,
	GREATER_EQUAL,
	LESS_EQUAL,
};
static const QHash<NodeType, QString> labels {
	{REALS, "ℝ"},
	{POSITIVE_REALS, "ℝ⁺"},
	{NEGATIVE_REALS, "ℝ⁻"},
	{INTEGERS, "ℤ"},
	{NATURAL_NUMS, "ℕ"},
	{IDENTIFIER, "id"},
	{NUMBER, "num"},
	{ADDITION, "+"},
	{SUBTRACTION, "-"},
	{UNARY_MINUS, "-"},
	{MULTIPLICATION, "*"},
	{CROSS, "×"},
	{DOT, "⋅"},
	{IN, "∈"},
	{NOT_IN, "∉"},
	{EQUAL, "="},
	{NOT_EQUAL, "≠"},
	{SUMMATION, "Σ"},
	{LOGICAL_NOT, "¬"},
	{LOGICAL_AND, "∧"},
	{LOGICAL_OR, "∨"},
	{INTEGRAL, "∫"},
	{FACTORIAL, "!"},
	{MULTIFACTORIAL, "!"},
	{GREATER, ">"},
	{LESS, "<"},
	{GREATER_EQUAL, "≥"},
	{LESS_EQUAL, "≤"},
};
